### ISSUE TITLE
Can FGR  input three or more pointclouds simultaneously ,and output the pose between them?

### ISSUE THREAD

**Issue by 18500864609** [IntelVCL/FastGlobalRegistration#18]
Hello，Professor Zhou, I entered the characteristics of the five sets of point clouds into the app, but the output parameters are still a group. Is it wrong with me?

**Comment by qianyizh** [comment]
The app only have 2-way registration. Multi-way registration is pretty hard to set up and is not included in this repo.

**Comment by 18500864609** [comment]
ok，Thank you for your reply! I find your open3D have this function

**Comment by 18500864609** [comment]
hello，I have read the instruction of Multi-way registration，and the paper “**Robust Reconstruction of Indoor Scenes**” 。I find it hard to understand the "line process",then I read the paper "**On the Unification of Line Processes, Outlier Rejection, and Robust Statistics with Applications in Early Vision**,still not understanding，我查了下这个算法，好像国内没有人用，或者说这个算法有个另外的中文名字，从文献上看这个line processes 已经被研究的很成熟了，你看能否给我点提示……thankyou

**Comment by 18500864609** [comment]
thanks for your reply,now I 'll try to compile the open3D to an android so library.Good luck to me ,haha !
