### ISSUE TITLE
Usage of Line process(r2 variable or psi(Ψ))

### ISSUE THREAD

**Issue by eclipse0922** [IntelVCL/FastGlobalRegistration#4]
In the part 3.2 of your paper, line process doesn't need to be calculated during the optimization of T.

If my understanding is right, we don't have to calculate line process for pair-to-pair registration .

For global registration, line process is needed. of course.

so, in the source code, variable r2 seems useless.
because there is no usage of r2 at all.
```
double r2 = 0.0;
		for (int c = 0; c < corres_.size(); c++) {
			int ii = corres_[c].first;
			int jj = corres_[c].second;
			Eigen::Vector3f p, q;
			p = pointcloud_[i][ii];
			q = pcj_copy[jj];
			Eigen::Vector3f rpq = p - q;

			int c2 = c;

			float temp = par / (rpq.dot(rpq) + par);
			s[c2] = temp * temp;

			J.setZero();
			J(1) = -q(2);
			J(2) = q(1);
			J(3) = -1;
			r = rpq(0);
			JTJ += J * J.transpose() * s[c2];
			JTr += J * r * s[c2];
			r2 += r * r * s[c2];

			J.setZero();
			J(2) = -q(0);
			J(0) = q(2);
			J(4) = -1;
			r = rpq(1);
			JTJ += J * J.transpose() * s[c2];
			JTr += J * r * s[c2];
			r2 += r * r * s[c2];

			J.setZero();
			J(0) = -q(1);
			J(1) = q(0);
			J(5) = -1;
			r = rpq(2);
			JTJ += J * J.transpose() * s[c2];
			JTr += J * r * s[c2];
			r2 += r * r * s[c2];

			r2 += (par * (1.0 - sqrt(s[c2])) * (1.0 - sqrt(s[c2])));
```

**Comment by syncle** [comment]
Sorry for the late reply, I am back from deadline mode.

If my understanding is right, we don't have to calculate line process for pair-to-pair registration. For global registration, line process is needed. of course.
> Nope. The line process is defined for every correspondences. Therefore, regardless of two cases: pairwise or multiway registration we update line process for every point correspondences. Here, the term 'global' used in our paper means non-local registration. Compared to local registration, non-local registration does not affected by initial pose. The example of local registration is ICP families, and example of global registration is GoICP, OpenCV, Super4PCS, PCL, CZK, and Ours.

> so, in the source code, variable r2 seems useless
You're right. r2 is just for checking whether objective is decreasing after iteration. It is legacy variable we had used when we tested algorithm.
